#!/usr/bin/env bash

set -euo pipefail

if (( $# < 2 || $# > 4 )); then
	echo "Usage: $0 <dependency-prefix> <jobs> [C compiler] [C++ compiler]" >&2
	exit 2
fi

prefix=$1
jobs=$2
cc=${3:-$(command -v clang)}
cxx=${4:-$(command -v clang++)}
source_dir="$PWD/clspv"
build_dir="$source_dir/build"
install_dir="$prefix/CLSPV"
chipstar_source_dir="$PWD/chipStar"
chipstar_install_dir="$prefix/CHIPSTAR"

if [[ "$(uname -s)" == "Darwin" ]]; then
	if ! command -v brew >/dev/null 2>&1; then
		echo "Homebrew is required to install MoltenVK and Vulkan-Headers on macOS" >&2
		exit 1
	fi
	brew install molten-vk vulkan-headers
fi

rm -rf "$source_dir" "$install_dir" "$chipstar_source_dir" "$chipstar_install_dir"
mkdir -p "$prefix"
git clone --depth 1 https://github.com/google/clspv.git "$source_dir"
git clone --depth 1 --recurse-submodules --shallow-submodules \
	https://github.com/CHIP-SPV/chipStar.git "$chipstar_source_dir"

cd "$source_dir"
python3 utils/fetch_sources.py

generator_args=()
if command -v ninja >/dev/null 2>&1; then
	generator_args=(-G Ninja)
fi

cmake -S "$source_dir" -B "$build_dir" "${generator_args[@]}" \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX="$install_dir" \
	-DCMAKE_C_COMPILER="$cc" \
	-DCMAKE_CXX_COMPILER="$cxx"
cmake --build "$build_dir" --parallel "$jobs"
cmake --install "$build_dir"

# clspv's top-level install exports clspv itself but not the matching LLVM
# tools and development libraries used by OpenFPM's translation pipeline.
for component in \
	llvm-headers LLVMDemangle LLVMSupport LLVMTargetParser LLVMBinaryFormat \
	LLVMBitstreamReader LLVMRemarks LLVMCore LLVMBitReader LLVMAsmParser \
	LLVMIRReader llvm-config clang clang-headers clang-resource-headers \
	llvm-link opt
do
	cmake -DCMAKE_INSTALL_COMPONENT="$component" \
		-DCMAKE_INSTALL_PREFIX="$install_dir" \
		-P "$build_dir/third_party/llvm/cmake_install.cmake"
done

for tool in \
	"$install_dir/bin/clspv" \
	"$install_dir/bin/clspv-reflection" \
	"$install_dir/bin/clang++" \
	"$install_dir/bin/opt" \
	"$install_dir/bin/llvm-link" \
	"$install_dir/bin/llvm-config"
do
	if [[ ! -x "$tool" ]]; then
		echo "CLSPV installation is missing required tool: $tool" >&2
		exit 1
	fi
done

# OpenFPM uses chipStar's HIP frontend headers and OpenCL device library, not
# its Vulkan/OpenCL runtime. Preserve the source layout expected by --hip-path
# without installing unneeded chipStar executables and runtime libraries.
cmake -E copy_directory "$chipstar_source_dir/HIP" "$chipstar_install_dir/HIP"
cmake -E copy_directory "$chipstar_source_dir/include" "$chipstar_install_dir/include"
cmake -E copy_directory "$chipstar_source_dir/bitcode" "$chipstar_install_dir/bitcode"

hip_version_values=($(sed -n '/^[0-9][0-9]*$/p' "$chipstar_source_dir/HIP/VERSION"))
hip_git_hash=$(git -C "$chipstar_source_dir" rev-parse --short HEAD)
mkdir -p "$chipstar_install_dir/HIP/include/hip"
printf '%s\n' \
	'// Auto-generated by install_CLSPV.sh' \
	'#ifndef HIP_VERSION_H' \
	'#define HIP_VERSION_H' \
	"#define HIP_VERSION_MAJOR ${hip_version_values[0]}" \
	"#define HIP_VERSION_MINOR ${hip_version_values[1]}" \
	"#define HIP_VERSION_PATCH ${hip_version_values[2]}" \
	"#define HIP_VERSION_GITHASH \"$hip_git_hash\"" \
	'#define HIP_VERSION_BUILD_ID 0' \
	'#define HIP_VERSION_BUILD_NAME "chipStar"' \
	'#define HIP_VERSION (HIP_VERSION_MAJOR * 10000000 + HIP_VERSION_MINOR * 100000 + HIP_VERSION_PATCH)' \
	'#define __HIP_HAS_GET_PCH 0' \
	'#endif' > "$chipstar_install_dir/HIP/include/hip/hip_version.h"
printf '%s\n' \
	'#ifndef CHIP_CONFIG_H' \
	'#define CHIP_CONFIG_H' \
	'#define CHIPSTAR_MAJOR_VERSION 1' \
	'#define CHIPSTAR_MINOR_VERSION 1' \
	'#define CHIPSTAR_PATCH_VERSION 0' \
	'#define CHIPSTAR_VERSION "1.1.0"' \
	'#define CHIP_DEFAULT_WARP_SIZE 32' \
	'#define CHIP_DEBUG_BUILD 0' \
	'#define HAS_FILESYSTEM 1' \
	"#define CHIP_INSTALL_DIR \"$chipstar_install_dir\"" \
	"#define CHIP_CLANG_PATH \"$install_dir/bin/clang++\"" \
	"#define LLVM_TOOLS_BINARY_DIR \"$install_dir/bin\"" \
	'#endif' > "$chipstar_install_dir/include/chipStarConfig.hh"

for required in \
	"$chipstar_install_dir/HIP/include/hip/hip_runtime.h" \
	"$chipstar_install_dir/HIP/include/hip/hip_version.h" \
	"$chipstar_install_dir/include/chipStarConfig.hh" \
	"$chipstar_install_dir/include/hip/devicelib/macOS" \
	"$chipstar_install_dir/bitcode/devicelib.cl"
do
	if [[ ! -e "$required" ]]; then
		echo "chipStar installation is missing required path: $required" >&2
		exit 1
	fi
done
